version: "3.9"

services:
  app:
    build: .
    depends_on:
      - pgdb
    restart: on-failure

  pgdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: "jopa"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_DB: "job_alerts"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always

volumes:
  db_data:
