google:
  id: "google-backend-job-alert"
  page-limit: 1
  link: "https://www.google.com/about/careers/applications/jobs/results?q=%22Software%20Engineer%20III%22&jlo=en-GB&location=Zurich%2C%20Switzerland&location=New%20York%2C%20NY%2C%20USA&location=California%2C%20USA&skills=backend"

db:
  user: "jopa"
  password: "env:PG_PASSWORD"
  address: "pgdb:5432"
  db-name: "job_alerts"

telegram:
  token: "env:TG_TOKEN"
  chat-id: "env:TG_CHAT_ID"
